/**
 * Design-language tokens carried into the exported scaffold.
 *
 * GENERATED from app/globals.css — do not edit by hand.
 *   node scripts/design-tokens.mjs --write
 *
 * The stylesheet remains the source of truth. The scaffold cannot import
 * from Elvin, so it takes a literal copy; `--check` fails whenever the copy
 * and the stylesheet disagree.
 */

export const DESIGNS = ["swiss", "brutalist", "biophilic", "minimal", "organic", "skeuomorphic", "cyberpunk"] as const;
export type Design = (typeof DESIGNS)[number];
export type Theme = "dark" | "light";

/** Google Fonts request for each language, taken from the stylesheet import. */
export const DESIGN_FONTS: Record<Design, string> = {
  swiss: "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap",
  brutalist: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&family=Space+Mono:wght@400;700&display=swap",
  biophilic: "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,100..900&family=Nunito+Sans:opsz,wght@6..12,200..1000&display=swap",
  minimal: "https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100..1000&display=swap",
  organic: "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@200..800&family=Quicksand:wght@300..700&display=swap",
  skeuomorphic: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400..900&family=Lora:wght@400..700&display=swap",
  cyberpunk: "https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&family=JetBrains+Mono:wght@100..800&display=swap",
};

/** Geometry, rhythm and type register. Names are the scaffold's own. */
export const DESIGN_TOKENS: Record<Design, Record<string, string>> = {
  swiss: {
    "--radius": "0px",
    "--radius-card": "0px",
    "--border-width": "2px",
    "--shadow": "none",
    "--label-weight": "600",
    "--label-tracking": ".08em",
    "--label-transform": "uppercase",
    "--heading-weight": "800",
    "--heading-tracking": "-.02em",
    "--body-size": "15px",
    "--pad-canvas": "24px",
    "--pad-section": "14px 16px",
    "--pad-bar": "12px 20px",
    "--pad-gap": "10px",
    "--danger": "#ae1800",
    "--font-heading": "\"Inter\", system-ui, sans-serif",
    "--font-body": "\"Inter\", system-ui, sans-serif",
    "--font-mono": "ui-monospace, Menlo, monospace",
  },
  brutalist: {
    "--radius": "0px",
    "--radius-card": "0px",
    "--border-width": "3px",
    "--shadow": "5px 5px 0 #000000",
    "--label-weight": "700",
    "--label-tracking": ".04em",
    "--label-transform": "uppercase",
    "--heading-weight": "700",
    "--heading-tracking": "-.03em",
    "--body-size": "15px",
    "--pad-canvas": "16px",
    "--pad-section": "11px 14px",
    "--pad-bar": "10px 16px",
    "--pad-gap": "8px",
    "--danger": "#b33500",
    "--font-heading": "\"Space Grotesk\", system-ui, sans-serif",
    "--font-body": "\"Space Grotesk\", system-ui, sans-serif",
    "--font-mono": "\"Space Mono\", ui-monospace, Menlo, monospace",
  },
  biophilic: {
    "--radius": "999px",
    "--radius-card": "18px",
    "--border-width": "1px",
    "--shadow": "0 10px 30px -14px rgba(30, 51, 32, .35)",
    "--label-weight": "600",
    "--label-tracking": ".01em",
    "--label-transform": "none",
    "--heading-weight": "600",
    "--heading-tracking": "-.01em",
    "--body-size": "16px",
    "--pad-canvas": "34px",
    "--pad-section": "20px",
    "--pad-bar": "16px 24px",
    "--pad-gap": "12px",
    "--danger": "#1d5034",
    "--font-heading": "\"Fraunces\", Georgia, ui-serif, serif",
    "--font-body": "\"Nunito Sans\", system-ui, sans-serif",
    "--font-mono": "ui-monospace, Menlo, monospace",
  },
  minimal: {
    "--radius": "3px",
    "--radius-card": "4px",
    "--border-width": "1px",
    "--shadow": "none",
    "--label-weight": "400",
    "--label-tracking": ".02em",
    "--label-transform": "none",
    "--heading-weight": "500",
    "--heading-tracking": "-.01em",
    "--body-size": "14px",
    "--pad-canvas": "40px",
    "--pad-section": "22px",
    "--pad-bar": "18px 28px",
    "--pad-gap": "14px",
    "--danger": "#ae1800",
    "--font-heading": "\"DM Sans\", system-ui, sans-serif",
    "--font-body": "\"DM Sans\", system-ui, sans-serif",
    "--font-mono": "ui-monospace, Menlo, monospace",
  },
  organic: {
    "--radius": "22px",
    "--radius-card": "30px",
    "--border-width": "2px",
    "--shadow": "0 12px 26px -14px rgba(70, 58, 42, .5)",
    "--label-weight": "600",
    "--label-tracking": ".04em",
    "--label-transform": "none",
    "--heading-weight": "600",
    "--heading-tracking": "-.015em",
    "--body-size": "16px",
    "--pad-canvas": "32px",
    "--pad-section": "20px",
    "--pad-bar": "14px 22px",
    "--pad-gap": "12px",
    "--danger": "#853621",
    "--font-heading": "\"Bricolage Grotesque\", system-ui, sans-serif",
    "--font-body": "\"Quicksand\", system-ui, sans-serif",
    "--font-mono": "ui-monospace, Menlo, monospace",
  },
  skeuomorphic: {
    "--radius": "8px",
    "--radius-card": "12px",
    "--border-width": "1px",
    "--shadow": "inset 0 1px 0 rgba(255, 255, 255, .75), 0 2px 3px rgba(60, 48, 30, .28)",
    "--label-weight": "700",
    "--label-tracking": ".12em",
    "--label-transform": "uppercase",
    "--heading-weight": "700",
    "--heading-tracking": "0",
    "--body-size": "16px",
    "--pad-canvas": "30px",
    "--pad-section": "18px",
    "--pad-bar": "14px 22px",
    "--pad-gap": "12px",
    "--danger": "#1a4469",
    "--font-heading": "\"Playfair Display\", Georgia, ui-serif, serif",
    "--font-body": "\"Lora\", Georgia, ui-serif, serif",
    "--font-mono": "ui-monospace, Menlo, monospace",
  },
  cyberpunk: {
    "--radius": "0px",
    "--radius-card": "2px",
    "--border-width": "1px",
    "--shadow": "0 0 14px color-mix(in srgb, #39ff88 34%, transparent)",
    "--label-weight": "700",
    "--label-tracking": ".18em",
    "--label-transform": "uppercase",
    "--heading-weight": "800",
    "--heading-tracking": ".04em",
    "--body-size": "14px",
    "--pad-canvas": "20px",
    "--pad-section": "12px 14px",
    "--pad-bar": "10px 16px",
    "--pad-gap": "8px",
    "--danger": "#1f9e53",
    "--font-heading": "\"Orbitron\", system-ui, sans-serif",
    "--font-body": "\"JetBrains Mono\", ui-monospace, Menlo, monospace",
    "--font-mono": "\"JetBrains Mono\", ui-monospace, Menlo, monospace",
  },
};

/** Sandbox palette, resolved for the selected theme. */
export const DESIGN_PALETTE: Record<Design, Record<Theme, Record<string, string>>> = {
  swiss: {
    dark: {
      "--a-bg": "#111111",
      "--a-fg": "#ededed",
      "--a-muted": "#a1a1a1",
      "--a-border": "#2e2e2e",
      "--a-surface": "#222222",
      "--a-chrome": "#171717",
      "--a-accent": "#ededed",
      "--a-accent-fg": "#111111",
    },
    light: {
      "--a-bg": "#ffffff",
      "--a-fg": "#0a0a0a",
      "--a-muted": "#737373",
      "--a-border": "#e5e5e5",
      "--a-surface": "#f4f4f5",
      "--a-chrome": "#fafafa",
      "--a-accent": "#0a0a0a",
      "--a-accent-fg": "#ffffff",
    },
  },
  brutalist: {
    dark: {
      "--a-bg": "#141414",
      "--a-fg": "#fffdf5",
      "--a-muted": "#b9ad86",
      "--a-border": "#fffdf5",
      "--a-surface": "#2b2b2b",
      "--a-chrome": "#1c1c1c",
      "--a-accent": "#ffe14d",
      "--a-accent-fg": "#000000",
    },
    light: {
      "--a-bg": "#fffdf5",
      "--a-fg": "#000000",
      "--a-muted": "#737373",
      "--a-border": "#000000",
      "--a-surface": "#ffe14d",
      "--a-chrome": "#fbf6e4",
      "--a-accent": "#000000",
      "--a-accent-fg": "#ffe14d",
    },
  },
  biophilic: {
    dark: {
      "--a-bg": "#0e1710",
      "--a-fg": "#e6efe4",
      "--a-muted": "#8ba184",
      "--a-border": "#26382a",
      "--a-surface": "#16241a",
      "--a-chrome": "#121d15",
      "--a-accent": "#6cbf8b",
      "--a-accent-fg": "#0e1710",
    },
    light: {
      "--a-bg": "#f7fbf5",
      "--a-fg": "#1e3320",
      "--a-muted": "#737373",
      "--a-border": "#d5e3cf",
      "--a-surface": "#e4efe1",
      "--a-chrome": "#eef6ec",
      "--a-accent": "#2f7d4f",
      "--a-accent-fg": "#f7fbf5",
    },
  },
  minimal: {
    dark: {
      "--a-bg": "#121212",
      "--a-fg": "#ededed",
      "--a-muted": "#a1a1a1",
      "--a-border": "#262626",
      "--a-surface": "#1b1b1b",
      "--a-chrome": "#161616",
      "--a-accent": "#ededed",
      "--a-accent-fg": "#111111",
    },
    light: {
      "--a-bg": "#ffffff",
      "--a-fg": "#0a0a0a",
      "--a-muted": "#737373",
      "--a-border": "#ececec",
      "--a-surface": "#f7f7f7",
      "--a-chrome": "#fcfcfc",
      "--a-accent": "#0a0a0a",
      "--a-accent-fg": "#ffffff",
    },
  },
  organic: {
    dark: {
      "--a-bg": "#241f1a",
      "--a-fg": "#efe6d7",
      "--a-muted": "#a99c86",
      "--a-border": "#3d352c",
      "--a-surface": "#2f2822",
      "--a-chrome": "#292320",
      "--a-accent": "#e0805d",
      "--a-accent-fg": "#241f1a",
    },
    light: {
      "--a-bg": "#fdf9f1",
      "--a-fg": "#36302a",
      "--a-muted": "#857a67",
      "--a-border": "#e3d8c6",
      "--a-surface": "#f3ead9",
      "--a-chrome": "#f8f1e4",
      "--a-accent": "#c2593a",
      "--a-accent-fg": "#fdf9f1",
    },
  },
  skeuomorphic: {
    dark: {
      "--a-bg": "#1c1710",
      "--a-fg": "#efe6d2",
      "--a-muted": "#a1927a",
      "--a-border": "#3a3122",
      "--a-surface": "#262019",
      "--a-chrome": "#211b14",
      "--a-accent": "#5f9dd4",
      "--a-accent-fg": "#1c1710",
    },
    light: {
      "--a-bg": "#fbf6e9",
      "--a-fg": "#33291c",
      "--a-muted": "#7b6e58",
      "--a-border": "#cdbf9f",
      "--a-surface": "#efe5cf",
      "--a-chrome": "#f4ecd8",
      "--a-accent": "#2a6fb0",
      "--a-accent-fg": "#fbf6e9",
    },
  },
  cyberpunk: {
    dark: {
      "--a-bg": "#05070a",
      "--a-fg": "#c6ffe0",
      "--a-muted": "#5f8f76",
      "--a-border": "#1b3a2a",
      "--a-surface": "#0b1210",
      "--a-chrome": "#080d0b",
      "--a-accent": "#39ff88",
      "--a-accent-fg": "#05070a",
    },
    light: {
      "--a-bg": "#eaf5ec",
      "--a-fg": "#0d2418",
      "--a-muted": "#5b7a68",
      "--a-border": "#bfd9c7",
      "--a-surface": "#dcecdf",
      "--a-chrome": "#e4f1e7",
      "--a-accent": "#137a44",
      "--a-accent-fg": "#eaf5ec",
    },
  },
};
